### PR TITLE
tags and metrics/datapoints deletion support

### PR DESCRIPTION
**Pull request by nellysmitt**
Hi! 
I am an Openstack intern and I'm writing a driver for KairosDB with Cassandra. I'm using your client and figured out that some functions are not implemented. I implemented tags search support and metrics and data points deletion since I needed this functionality for my driver. My mentor said that these changes should be official, so I'm creating a pull request. Please, review and merge if possible. This is quite urgent... Thanks :)

### CODE REVIEW

**Comment by pcn** [comment]
I'm happy to commit, but let me ask - do you have tests for this?

**Comment by pcn** [comment]
Ugghh... I'm sick.  I am happy to merge this, it looks fine at first glance.  However do you have tests - either automated tests or a test plan that can be used to reproduce the desired behavior?  If so, whatever you've got needs to be included here.  If not, please put something together and add it to this branch.

**Comment by nellysmitt** [comment]
It's working in my driver so far... I'll make tests and include them then.

**Comment by pcn** [comment]
Thanks!

**Comment by pcn** [comment]
I just realized that your native language may not be English so please don't worry about the language being impeccable.  I'm happy to do further editing.

**Comment by nellysmitt** [comment]
Hey

It took so long to add tests because I was waiting to reply from Kairos guys. Actually, they didn't reply. The problem is that 2 tests are failing due to unknown reason. I suspect search by tag may be not supported for Cassandra. Did reads ever work with 'only_read_tags=True' for Cassandra?

Other tests are fine.

**Comment by pcn** [comment]
I'll have to do some research into only_read_tags - I believe it was an optimization that I asked for, but I had to emulate the behavior in my original implementation.

**Pull request merged**
